### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by brianyu14519** [jordanb84/Raspberry-Pi-Group-Bot#5]
On the command ping, (,ping) it shows the argument ping and or every other work you put down after. ex ,ping hi 123 : Ping! [arguments ping, hi, 123]

**Comment by jordanb84** [comment]
That is the intended functionality. While those are not the arguments required for the command, they are the arguments that you are attempting to pass to the command, which the command will verify/attempt to use.

As for the command identifier being included in that, this is for commands that may want to make slight changes to their functionality based on it. This feature became useful in Cowsay.

Thanks, though!
